
namespace imajuscule {
    namespace testrng {
        void test(bool create_ref)
        {
            using T = decltype(mersenne<SEEDED::Yes>()());
            
            std::vector<std::vector<T>> ref {{
                // DO NOT EDIT : generated by test when ppassing true for create_ref
                {{
                    2357136044,
                    2546248239,
                    3071714933,
                    3626093760,
                    2588848963,
                    3684848379,
                    2340255427,
                    3638918503,
                    1819583497,
                    2678185683,
                }},
                {{
                    1791095845,
                    4282876139,
                    3093770124,
                    4005303368,
                    491263,
                    550290313,
                    1298508491,
                    4290846341,
                    630311759,
                    1013994432,
                }},
                {{
                    1872583848,
                    794921487,
                    111352301,
                    4000937544,
                    2360782358,
                    4070471979,
                    1869695442,
                    2081981515,
                    1805465960,
                    1376693511,
                }},
                {{
                    2365658986,
                    303761048,
                    3041471737,
                    3607553667,
                    1249426360,
                    521102280,
                    2193987840,
                    2445173525,
                    3835177981,
                    1877166739,
                }},
                {{
                    4153361530,
                    3868139694,
                    2350344631,
                    741720773,
                    4177647489,
                    3674863976,
                    3070111319,
                    2615787976,
                    2996722482,
                    2566484361,
                }},
                // DO NOT EDIT (END)
            }};
            
            using namespace std;
            for(int i=0; i<5; i++) {
                mersenne<SEEDED::Yes>().seed(i);
                if(create_ref) {
                    cout << "{{" << endl;
                }
                for(int j=0; j<10; ++j) {
                    auto v = mersenne<SEEDED::Yes>()();
                    if(create_ref) {
                        cout << v << "," << endl;
                    }
                    else {
                        ASSERT_EQ(v, ref[i][j]);
                    }
                }
                if(create_ref) {
                    cout << "}}," << endl;
                }
            }
        }
    }
}

TEST(RNG,mersenne) {
    // verify that rng of seeded mersenne gives the same values on each platform,
    // because we rely on that to defind birds songs
    using namespace imajuscule::testrng;
    constexpr bool create_ref = false;
    // uncomment to generate reference (std::cout)
    //test(true);
    test(create_ref);
}
