#pragma once

#include <array>
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <ctime>
#include <cxxabi.h>
#include <functional>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <list>
#include <map>
#include <new>
#include <unordered_map>
#include <memory>
#include <random>
#include <stdio.h>
#include <string>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <utility>
#include <vector>

#include "meta.hpp"
#include "math.hpp"
#include "numtraits.h"
#include "freelist.hpp"
#include "complex.h"
#include "range.h"
#include "strplot.h"
#include "rng.hpp"
#include "markov_chain.hpp"
#include "safe_cast.hpp"
#include "print_type.hpp"
#include "pool.adaptive_stack.h"
#include "allocator.adaptive_stack.hpp"
#include "allocator.aligned.hpp"
#include "allocated_containers.h"
#include "static_vector.h"
#include "iter_range.hpp"
#include "sort_utils.hpp"
#include "insertion_sort.hpp"
#include "heap_sort.hpp"
#include "bounded_lifo.hpp"
#include "hash.hpp"
#include "hash_table.hpp"
#include "merge_sort.hpp"

